# Generated by Django 3.2.3 on 2021-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('primeira_avaliacao', models.CharField(max_length=30)),
                ('segunda_avaliacao', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
