# Generated by Django 3.2.3 on 2021-06-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frases', '0002_auto_20210603_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
